version: '2'
services:
  redis:
    image: redis
    ports: 
        - "6379:6379"
  server: 
    build: server
    volumes:
    - ./server:/app
    - /app/node_modules
    ports: 
        - "3000:3000"
    depends_on:
        - redis
  client: 
    build: .
    volumes:
    - ./:/app
    ports: 
        - "8000:8000"
    depends_on:
        - server